#:kivy 2.0.0
<ConspiracyBoard>:
    Widget:

        Scatter:
            id: scatter
            size_hint: None, None
            pos: (200, 200)

            Label:
                text: 'My spoon is too big'
                text_size: self.width, None

        Scatter:
            id: scatter2
            size_hint: None, None

            Label:
                text: 'I am a banana'
                text_size: self.width, None
